version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  exportedVariables:
    - version
    
steps:
  - type: Command
    name: "Build Source 1"
    timeoutInSeconds: 400
    command: |
      mvn clean install
  - type: Command
      timeoutInSeconds: 400
      name: "Dockerizer"
      command: |
        version=`echo ${OCI_BUILD_RUN_ID} | rev | cut -c 1-7`
        echo $version
outputArtifacts:
  - name: OUTPUT
    type: BINARY
    location: ${OCI_WORKSPACE_DIR}/helloWorld/pom.xml
