version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash

steps:
  - type: Command
    name: "Build Source 1"
    timeoutInSeconds: 400
    command: |
      mvn clean install

outputArtifacts:
  - name: OUTPUT
    type: BINARY
    location: target/helloWorld-0.0.1.jar
